baseURL = "http://turvolonter76.ru"
languageCode = "en-us"
theme = "ananke"
title = "Центр туристских волонтеров"

DefaultContentLanguage = "ru"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/images/q.jpg"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  Vk = "https://vk.com/yarturvolonter"
  instagram = ""
  youtube = "https://www.youtube.com/watch?v=EqSclLcbvCA"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-beige"
  featured_image = "/images/pp.jpg"
  recent_posts_number = 2